# Define the chart name you want for this chart, then define the charts you want to package in this module as 
# dependencies. You can then run `helm dependency update` on this folder and Helm will take care to populate the charts 
# subfolder with every chart packaged in a `.tar.gz`.
---
apiVersion: "v2"
name: "jaeger"
version: "0"
dependencies:
  - name: "jaeger"
    version: "0.71.2" # Fix the major version only.
    repository: "https://jaegertracing.github.io/helm-charts"
